apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/add-anonymous-user-filter
    name: add-anonymous-user-filter  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/profile-control-plane2
    name: kubeflow-apps  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/katib
    name: katib  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/argo
    name: argo  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/minio/installs/generic
    name: minio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/notebooks2
    name: notebooks
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/pytorch-job
    name: pytorch-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/tf-job
    name: tf-job  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving  
  repos:
  - name: manifests
    uri: file:{local_repo}
  version: ai_devops.v1.2.5.0
