FROM docker.io/tmaxcloudck/jupyterlab-kale:b1.0.0
USER root
WORKDIR /kale/backend
RUN pip3 install "torch"
RUN pip3 install "torchvision"
RUN pip3 install "pandas"
RUN pip3 install "seaborn"
RUN pip3 install "sklearn"
